#!/usr/bin/env bash
sh buildDebianBase.sh
sh buildConsul.sh
sh buildOpenjdk-jre.sh
sh buildOpenjdk-jdk.sh
sh buildMongodb.sh
sh buildPostgres.sh
sh buildRedisOrSentinel.sh
sh buildRabbitMQ.sh
sh buildZookeeper.sh
sh buildKafka.sh
sh buildNginx.sh
sh buildNexus.sh
sh buildOpenResty.sh