#!/usr/bin/env bash
sh buildDebianBase.sh
sh buildIdeaLicenseServer.sh
sh buildOpenjdk-jre.sh
sh buildMongodb.sh
sh buildPostgres.sh
sh buildRedisOrSentinel.sh
sh buildRabbitMQ.sh
sh buildZookeeper.sh
sh buildKafka.sh
sh buildNginx.sh
